MyBank/Models/Compute.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace MyBank.Models
{
    public class Compute
    {
        public string ComputeMd5Hash(string message)
        {
            using (MD5 md5 = MD5.Create())
            {
                byte[] input = Encoding.ASCII.GetBytes(message);
                byte[] hash = md5.ComputeHash(input);
        
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hash.Length; i++)
                {
                    sb.Append(hash[i].ToString("X2"));
                }
                return sb.ToString().ToLower();
            }
        } 
    }
}

MyBank/Models/ErrorViewModel.cs
using System;

namespace MyBank.Models
{
    public class ErrorViewModel
    {
        public string ErrorMessage { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(ErrorMessage);
    }
}

MyBank/Models/Home.cs
using System;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Data;
using System.Configuration;
using System.Collections;
using Microsoft.AspNetCore.Http;

namespace MyBank.Models
{
    public class Home
    {
        public void RegisterBtn (Object sender, EventArgs args)
        {
            //Response.Redirect("");
        }
    }
}

MyBank/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using MyBank.Models;
using Microsoft.AspNetCore.Mvc;
using MyBank.Data.Repository.User;
using MyBank.Data.Repository.Login;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MyBank.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IRegisterRepository _registerRepository;
        private readonly ILoginRepository _loginRepository;
        Compute compute = new Compute();

        public AccountsController(IRegisterRepository registerRepository, ILoginRepository loginRepository)
        {
            _registerRepository = registerRepository;
            _loginRepository = loginRepository;
        }

        public IActionResult Register(User user)
        {
            if(string.IsNullOrEmpty(user.Email)) return View(user);

            int userCount =  _registerRepository.GetUserCount(user.Email);
            if(userCount > 0) 
            {
                return RedirectToAction("Register", new Login { LoginError = "This user already exists" });
            }
            
            user.DateCreated = DateTime.Now;
            _registerRepository.CreateUser(user);
            return RedirectToAction("CreatePassword");
        }

        public IActionResult Login(Login login)
        {
            if(string.IsNullOrEmpty(login.Email)) return View(login);

            int userCount =  _registerRepository.GetUserCount(login.Email);

            if(userCount > 0) 
            {
                bool loginExists = _loginRepository.GetLogin(login.Email, compute.ComputeMd5Hash(login.Password), true);
                if(loginExists)
                {
                    return Ok("User successfully logged in");
                }
                
                return RedirectToAction("Login", new Login { LoginError = "Invalid login credentials"});
            }

            return RedirectToAction("Login", new Login { LoginError = "User doesn't exist"});
        }

        public IActionResult CreatePassword(Login login)
        {
            if(string.IsNullOrEmpty(login.Email)) return View();

            login.Password = compute.ComputeMd5Hash(login.Password);
            _loginRepository.Createlogin(login);
            return RedirectToAction("Login");
        }

        public IActionResult Error(string errorMessage)
        {
            return View(new ErrorViewModel { ErrorMessage = errorMessage});
        } 
    }
}

MyBank/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyBank.Models;

namespace MyBank.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { ErrorMessage = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyBank/Views/Accounts/CreatePassword.cshtml
@model Login

@{
    ViewData["Title"] = "Create Password Page";
}

<div class="img js-fullheight" style="background-image: url(~wwwroot/images/bg.jpg);">
    <section class="ftco-section">
        <div class="">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section mt-5">MyBank</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        <h3 class="mb-4 text-center">Password Creation Page</h3>
                        @using (Html.BeginForm("CreatePassword", "Accounts", FormMethod.Post))
                        {
                            <div class="signin-form" id="appointment-form">
                                <div class="form-group-1">
                                    <p class="mb-5 text-secondary text-center">Account created. Please create login credentials</p>
                                    @Html.TextBoxFor(m => m.Email, new { @placeholder = "Email or Phone", @class = "bvn", @id = "email", @required = "required" })
                                    @Html.TextBoxFor(m => m.Password, new { type = "password", @placeholder = "Password", @class = "password", @id = "password", @required = "required" })
                                    @Html.TextBoxFor(m => m.Password, new { type = "password", @placeholder = "Confirm Password", @class = "password", @id = "password", @required = "required" })
                                </div>
                                <div class="form-submit">
                                    <input type="submit" name="submit" id="submit" class="submit" value="Create" />
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="js/jquery.min.js"></script>
    <script src="js/popper.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>

</div>

MyBank/Views/Accounts/Login.cshtml
@model MyBank.Models.Login;

@{
    ViewData["Title"] = "Login Page";
}

<div class="img js-fullheight" style="background-image: url(~wwwroot/images/bg.jpg);">
    <section class="ftco-section">
        <div class="">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section mt-5">MyBank</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        <h3 class="mb-4 text-center">Login Page</h3>
                        @if(Model != null)
                        {
                            @if (Model.loginErrorCheck) { <p class="text-danger mb-2">@Model.LoginError</p> }
                        }

                        @using (Html.BeginForm("Login", "Accounts", FormMethod.Post))
                        {
                            <div class="signin-form" id="appointment-form">
                                <div class="form-group-1">
                                    @Html.TextBoxFor(m => m.Email, new { @placeholder = "Email or Phone", @class = "bvn", @id = "email", @required = "required" })
                                    @Html.TextBoxFor(m => m.Password, new { type = "password", @placeholder = "Password", @class = "password", @id = "password", @required = "required" })
                                </div>
                                <div class="form-submit">
                                    <input type="submit" name="submit" id="submit" class="submit" value="Login" />
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="js/jquery.min.js"></script>
    <script src="js/popper.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>

</div>

MyBank/Views/Accounts/Register.cshtml
@model User;

@{
    ViewData["Title"] = "Registration Page";
}

@using (Html.BeginForm("Register", "Accounts", FormMethod.Post))

{
    <div class="appointment-form" id="appointment-form">
        <h2>Registration Page</h2>
        @if(Model != null)
        {
            @if (Model.loginErrorCheck) { <p class="text-danger mb-2">@Model.LoginError</p><br/> }
        }
        <div class="form-group-1">
            <h3>Personal Information</h3>
            <label class="label-color">Title</label>
            @Html.DropDownListFor(m => m.Title, new SelectList(Enum.GetValues(typeof(Title))), new { @placeholder = "Title" })
            @Html.TextBoxFor(m => m.Fname, new { @placeholder = "First Name", @class = "fname", @id = "fname", @required = "required" })
            @Html.TextBoxFor(m => m.Lname, new { @placeholder = "Last Name", @class = "lname", @id = "lname", @required = "required" })
            @Html.TextBoxFor(m => m.BVN, new { @placeholder = "BVN", @class = "bvn", @id = "bvn", @required = "required" })
            @Html.TextBoxFor(m => m.NIN, new { @placeholder = "NIN", @class = "nin", @id = "nin", @required = "required" })
            @Html.TextBoxFor(m => m.Occupation, new { @placeholder = "Occupation", @class = "occupation", @id = "occupation", @required = "required" })
            <label class="label-color">Date of Birth</label>
            @Html.TextBoxFor(m => m.DateofBirth, "{0:d MMM yyyy}", new { type = "date", @placeholder = "DOB", @class = "dob", @id = "dob", @required = "required" })
            <label class="label-color">Gender</label>
            @Html.DropDownListFor(m => m.GenderSelected, new SelectList(Enum.GetValues(typeof(Gender))), new { @placeholder = "Gender" })
            <label class="label-color">Marital Status</label>
            @Html.DropDownListFor(m => m.MaritalStatusSelected, new SelectList(Enum.GetValues(typeof(MaritalStatus))), new { @placeholder = "Marital Status" })
        </div>
        <div class="form-group-1"> 
            <h3>Contact Information</h3>
            @Html.TextBoxFor(m => m.Email, new { @placeholder = "Email", @required = "required" })
            @Html.TextBoxFor(m => m.PhoneNumber, new { @placeholder = "Phone Number", @required = "required" })
            @Html.TextBoxFor(m => m.Address, new { @placeholder = "Home Address", @required = "required" })
            @Html.TextBoxFor(m => m.State, new { @placeholder = "State", @required = "required" })
            @Html.TextBoxFor(m => m.Country, new { @placeholder = "Country", @required = "required" })
        </div><br />
        <div class="form-group-2">
            <h3>Means of Identification</h3>
            @Html.TextBoxFor(m => m.ID_Doc, new { type = "file", @required = "required" })
        </div>
        <div class="form-check">
            @Html.TextBoxFor(m => m.Agree, new { type = "checkbox" })
            @Html.LabelFor(m => m.Agree)
        </div>
        <div class="form-submit">
            <input type="submit" name="submit" id="submit" class="submit" value="Submit Form" />
        </div>
    </div>
}

MyBank/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="center text-center pt-5 pb-5">
    <h1 class="text-dark pb-4">MyBank</h1>
    <h4 class="text-secondary pb-2">The financial institution for all your needs</h4>
    <div class="d-grid gap-2 col-6 mx-auto">
        <input type="button" class="submit btn btn-primary mr-5 ml-5" value="Sign In" onclick="@("window.location.href='" + @Url.Action("Login", "Accounts") + "'");" />
        <input type="button" class="submit btn btn-primary mr-5 ml-5" value="Register" onclick="@("window.location.href='" + @Url.Action("Register", "Accounts") + "'");" />
    </div>
</div>

MyBank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyBank</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fonts/material-icon/css/material-design-iconic-font.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyBank</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="">
            &copy; 2022 - MyBank - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>